### PR TITLE
Change and correction in the french texte

### PR DESCRIPTION
**Pull request by 5axes**
Minor correction from french feedback

### CODE REVIEW

**Comment by 5axes** [comment]
I don't really understand why these files are in conflict ? and how to solve it

**Comment by 5axes** [comment]
experimental/infill_enable_travel_optimization.md

 it may increase the slicing time by orders of magnitude. ???  A value should characterize this increase in the orgiginal text ?

**Comment by Ghostkeeper** [comment]
> it may increase the slicing time by orders of magnitude. ??? A value should characterize this increase in the orgiginal text ?

Yes. In more technical terms, it changes the complexity of planning paths from O(N³) to O(N⁴). It has a fairly low constant factor, but the cost of deciding which infill line to print next is multiplied by the number of walls in your layer. If you have a lot of infill paths and a complex shape, it can take a long time.

There is no fixed value or fixed ratio that I can put in the original text, because it's a multiplication with a factor based on the user's model. I could put a complexity analysis in there but I don't think that really says anything to anyone. It will also be a bit misleading because the constant factor is usually low, and will need to be kept up to date if the algorithm changes.

**Comment by Ghostkeeper** [comment]
> I don't really understand why these files are in conflict ? and how to solve it

They are in conflict because I applied some changes after merging your previous PR, i.e. to remove that extra image. You didn't update your fork with my changes before making further corrections. So Git just sees that two people split off from the same version independently and now there's a conflict in which changes we made.

Here are some suggestions on how to fix it: https://stackoverflow.com/questions/161813/how-to-resolve-merge-conflicts-in-git

Myself I normally use `git fetch upstream && git merge upstream/master` and then resolve the conflicts in my IDE.

**Comment by 5axes** [comment]
> They are in conflict because I applied some changes after merging your previous PR, e.g. to remove that extra image

Ok I switch back some files and resolve other issue in conflicts with your current release.

**Comment by 5axes** [comment]
I will wait for the next Merge validation before to modify new files. And start from a new fork .

**Comment by 5axes** [comment]
ok I've also updated my fork based on your current release.

But i have some problems to integrate in the french text your conditional test <If cura ...   is it normal ?

**Comment by Ghostkeeper** [comment]
It's not normal to have problems. Whether or not the behaviour you're seeing is normal depends on the behaviour you're seeing. The keyword is case and space sensitive, mind you.

It's a new feature for the upcoming version. It's designed to work both when viewed on the web here on Github, and when viewed in the Settings Guide in Cura.

**Pull request merged**
