### PR TITLE
Last French translation

### PR DESCRIPTION
**Pull request by 5axes**
Last French Translation 

Some of the parameters are not translated in the Cura 5.0 Beta . So further modification must be done with the Release Version

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Yeah, we have some translations already. I can look those up for you.

I hope I'll be working on the rest of the articles for the Settings Guide update in the upcoming weekend (tomorrow). There's more to come. And I'll look up those translations for you then too.

**Comment by Ghostkeeper** [comment]
Here is a list of the French translations of all of the new settings in Cura 5.0. Note that not all of the articles are written yet in English at this point. I hope to get that done this weekend.

<table>
<tr>
	<td>Wall Transition Length
	<td>Longeur de transition de la paroi
<tr>
	<td>Wall Distribution Count
	<td>Nombre de distributions des parois
<tr>
	<td>Wall Transitioning Threshold Angle
	<td>Angle du seuil de transition de la paroi
<tr>
	<td>Wall Transitioning Filter Distance
	<td>Distance du filtre de transition des parois
<tr>
	<td>Wall Transitioning Filter Margin
	<td>Marge du filtre de transition des parois
<tr>
    <td>Wall Ordering
    <td>Ordre des parois
<tr>
    <td>Minimum Wall Line Width
    <td>Largeur minimale de la ligne de paroi
<tr>
    <td>Minimum Even Wall Line Width
    <td>Largeur minimale de la ligne de paroi uniforme
<tr>
    <td>Split Middle Line Threshold
    <td>Seuil de ligne médiane fractionnée
<tr>
    <td>Minimum Odd Wall Line Width
    <td>Largeur minimale de la ligne de paroi impaire
<tr>
    <td>Add Middle Line Threshold
    <td>Ajouter un seuil de ligne médiane
<tr>
    <td>Minimum Feature Size
    <td>Taille minimale des entités
<tr>
    <td>Minimum Thin Wall Line Width
    <td>Largeur minimale de la ligne de paroi fine
<tr>
    <td>Horizontal Scaling Factor Shrinkage Compensation
    <td>Compensation du rétrécissement du facteur d'échelle horizontale
<tr>
    <td>Vertical Scaling Factor Shrinkage Compensation
    <td>Compensation du rétrécissement du facteur d'échelle verticale
<tr>
    <td>Flow Equalization Ratio
    <td>Rapport d'égalisation des débits
<tr>
    <td>Skirt/Brim Extruder
    <td>Extrudeur de la jupe/bordure
<tr>
    <td>Raft Base Extruder
    <td>Extrudeur de la base du raft
<tr>
    <td>Raft Middle Extruder
    <td>Extrudeur du milieu du radeau
<tr>
    <td>Raft Top Extruder
    <td>Extrudeur du haut du radeau
<tr>
    <td>Raft Middle Layers
    <td>Couches du milieu du radeau
<tr>
    <td>Maximum Extrusion Area Deviation
    <td>Écart maximal de la surface d'extrusion
<tr>
    <td>Alternate Wall Directions
    <td>Alterner les directions des parois
<tr>
    <td>Remove Raft Inside Corners
    <td>Supprimer les coins intérieurs du radeau
<tr>
    <td>Raft Base Wall Count
    <td>Nombre de parois à la base du radeau
</table>

The current state of the setting translations can always be seen [here](https://github.com/Ultimaker/Cura/blob/master/resources/i18n/fr_FR/fdmprinter.def.json.po). But it's a bit obnoxious to find them there every time since it's such a long file. I hope this overview helps.

I do find some inconsistencies in there (e.g. one of the Raft settings kept using "raft" instead of "radeau"). Maybe we could get that taken a look at for Cura 5.1.

**Comment by Ghostkeeper** [comment]
The stable release for Cura 5.0 is planned for next Tuesday. I hope I can release my update on Monday, but it'll be hard for you to keep up with me then. I'm amazed at how you keep up with it so fast, but I can't expect of you to update the translations every day. So here's a proposal.

I'd like to submit the plug-in for review on Monday and get it reviewed on release day. Given the popularity of this guide and its usefulness to my colleagues they are usually quite willing to do that. I'll include the translations that you have then. And then a week or so later I could make a patch release with your updates if you have any then.

Does that sound okay?

**Comment by 5axes** [comment]
It's Ok for me .. 
Yes the : **Extrudeur de la base du raft**  Should be    : **_Extrudeur de la base du radeau_**   but it's really a detail

**Comment by 5axes** [comment]
According to your explanation in the min_even_wall_line_width  I think that the french translation 
Largeur minimale de la ligne de paroi paire   is better  as the proposed translation "Largeur minimale de la ligne de paroi uniforme"    I will keep this translation in my French explanation  to keep  :

Minimum **Even** Wall Line Width -> Largeur minimale des lignes de paroi **paire**
Minimum **Odd** Wall Line Width -> Largeur minimale des lignes de paroi **impaire**

**Review by Ghostkeeper — APPROVED** [review]
Thanks for the update. I couldn't find any problems with this at first glance.

I'll do a squash merge here since most of these commits don't have any commit message to them. That means though that Github won't see this PR as merged since it'll have different commit IDs. But it will get merged.

**Comment by Ghostkeeper** [comment]
Well, disregard that. The merge conflict in here messed up my rebase a bit. In the interest of time I'll just merge it like this.

**Pull request merged**
