### PR TITLE
minor tipo

### PR DESCRIPTION
**Pull request by 5axes**
minor texte and tipo correction

### CODE REVIEW

**Comment by 5axes** [comment]
error

**Comment by 5axes** [comment]
cannot resolve error

**Comment by Ghostkeeper** [comment]
What was wrong here? The changes seem innocuous to me. And the tests, as far as they've ran, have been succeeding, right?

**Comment by Ghostkeeper** [comment]
Ah, seems this was superseded by https://github.com/Ghostkeeper/SettingsGuide/pull/48.

**Pull request closed without merging**
