### PR TITLE
Adding a Czech translation

### PR DESCRIPTION
**Pull request by vb138**
I translated all articles into Czech

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Oof, that must have been a lot of work! Thanks a bunch!

The automated test is failing because links to the images are broken. These links to images are relative to the current path of the file, so in order to prevent having to duplicate all images, you'd need to change the `../images/some_image.png` into `../../../articles/images/some_image.png` everywhere.

I can automate that with a search and replace if you'd like some help. It is a bit technical, but necessary in order to make the images work when the articles are viewed in Github. Let me know if you want some help.

**Comment by vb138** [comment]
Thanks for the advice

**Comment by Ghostkeeper** [comment]
Tests are working now. I can give this a test after work tonight, I think.

**Comment by Ghostkeeper** [comment]
Link to my correction: https://github.com/Ghostkeeper/SettingsGuide/commit/e1496afaa2b08a00acd5d5e066655021bb7918a0

**Pull request merged**
